using System;
namespace RandomUser.Infrastructure.DataSeeding
{
    public class MaleNames
    {
        public static string[] names = { "John", "William", "James",
            "Charles", "George", "Frank", "Joseph", "Thomas", "Henry",
            "Robert", "Edward", "Harry", "Walter", "Arthur", "Fred",
            "Albert", "Samuel", "David", "Louis", "Joe", "Charlie",
            "Clarence", "Richard", "Andrew", "Daniel", "Ernest", "Will",
            "Jesse", "Oscar", "Lewis", "Peter", "Benjamin", "Frederick",
            "Willie", "Alfred", "Sam", "Roy", "Herbert", "Jacob", "Tom",
            "Elmer", "Carl", "Lee", "Howard", "Martin", "Michael", "Bert",
            "Herman", "Jim", "Francis", "Harvey", "Earl", "Eugene", "Ralph",
            "Ed", "Claude", "Edwin", "Ben", "Charley", "Paul", "Edgar",
            "Isaac", "Otto", "Luther", "Lawrence", "Ira", "Patrick", "Guy",
            "Oliver", "Theodore", "Hugh", "Clyde", "Alexander", "August",
            "Floyd", "Homer", "Jack", "Leonard", "Horace", "Marion",
            "Philip", "Allen", "Archie", "Stephen", "Chester", "Willis",
            "Raymond", "Rufus", "Warren", "Jessie", "Milton", "Alex",
            "Leo", "Julius", "Ray", "Sidney", "Bernard", "Dan", "Jerry",
            "Calvin", "Perry", "Dave", "Anthony", "Eddie", "Amos",
            "Dennis", "Clifford", "Leroy", "Wesley", "Alonzo",
            "Garfield", "Franklin", "Emil", "Leon", "Nathan",
            "Harold", "Matthew", "Levi", "Moses", "Everett", "Lester",
            "Winfield", "Adam", "Lloyd", "Mack", "Fredrick", "Jay", "Jess",
            "Melvin", "Noah", "Aaron", "Alvin", "Norman", "Gilbert", "Elijah",
            "Victor", "Gus", "Nelson", "Jasper", "Silas", "Jake", "Christopher",
            "Mike", "Percy", "Adolph", "Maurice", "Cornelius", "Felix", "Reuben",
            "Wallace", "Claud", "Roscoe", "Sylvester", "Earnest", "Hiram", "Otis",
            "Simon", "Willard", "Irvin", "Mark", "Jose", "Wilbur", "Abraham", "Virgil",
            "Clinton", "Elbert", "Leslie", "Marshall", "Owen", "Wiley", "Anton", "Morris",
            "Manuel", "Phillip", "Augustus", "Emmett", "Eli", "Nicholas", "Wilson", "Alva",
            "Harley", "Newton", "Timothy", "Marvin", "Ross", "Curtis", "Edmund", "Jeff",
            "Elias", "Harrison", "Stanley", "Columbus", "Lon", "Ora", "Ollie", "Pearl",
            "Russell", "Solomon", "Arch", "Asa", "Clayton", "Enoch", "Irving", "Mathew",
            "Nathaniel", "Scott", "Hubert", "Lemuel", "Andy", "Ellis", "Emanuel",
            "Joshua", "Millard", "Vernon", "Wade", "Cyrus", "Miles", "Rudolph", "Sherman",
            "Austin", "Bill", "Chas", "Lonnie", "Monroe", "Byron", "Edd", "Emery", "Grant",
            "Jerome", "Max", "Mose", "Steve", "Gordon", "Abe", "Pete", "Chris", "Clark",
            "Gustave", "Orville", "Lorenzo", "Bruce", "Marcus", "Preston", "Bob", "Dock",
            "Donald", "Jackson", "Cecil", "Barney", "Delbert", "Edmond", "Anderson",
            "Christian", "Glenn", "Jefferson", "Luke", "Neal", "Burt", "Ike", "Myron",
            "Tony", "Conrad", "Joel", "Matt", "Riley", "Vincent", "Emory", "Isaiah", 
            "Nick", "Ezra", "Green", "Juan", "Clifton", "Lucius", "Porter", "Arnold", 
            "Bud", "Jeremiah", "Taylor", "Forrest", "Roland", "Spencer", "Burton", "Don",
             "Emmet", "Gustav", "Louie", "Morgan", "Ned", "Van", "Ambrose", "Chauncey", 
             "Elisha", "Ferdinand", "General", "Julian", "Kenneth", "Mitchell", "Allie",
              "Josh", "Judson", "Lyman", "Napoleon", "Pedro", "Berry", "Dewitt", "Ervin", 
              "Forest", "Lynn", "Pink", "Ruben", "Sanford", "Ward", "Douglas", "Ole", "Omer",
               "Ulysses", "Walker", "Wilbert", "Adelbert", "Benjiman", "Ivan", "Jonas", "Major", 
               "Abner", "Archibald", "Caleb", "Clint", "Dudley", "Granville", "King", "Mary", 
               "Merton", "Antonio", "Bennie", "Carroll", "Freeman", "Josiah", "Milo", "Royal", "Dick",
                "Earle", "Elza", "Emerson", "Fletcher", "Judge", "Laurence", "Neil", "Roger", "Seth",
                 "Glen", "Hugo", "Jimmie", "Johnnie", "Washington", "Elwood", "Gust", "Harmon", "Jordan",
                  "Simeon", "Wayne", "Wilber", "Clem", "Evan", "Frederic", "Irwin", "Junius", "Lafayette", 
                  "Loren", "Madison", "Mason", "Orval", "Abram", "Aubrey", "Elliott", "Hans", "Karl", "Minor", 
                  "Wash", "Wilfred", "Allan", "Alphonse", "Dallas", "Dee", "Isiah", "Jason", "Johnny", "Lawson",
                   "Lew", "Micheal", "Orin", "Addison", "Cal", "Erastus", "Francisco", "Hardy", "Lucien", 
                   "Randolph", "Stewart", "Vern", "Wilmer", "Zack" };
        }
}

